#!/bin/sh -e

# /etc/cron.weekly/adblock-update

# Ensure we don't use an old file
rm -f /etc/hosts.pending

# Timestamp it
date +'# curled on %c' >> /etc/hosts.pending

# Fetch it
curl -Ss https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts \
	>> /etc/hosts.pending

# Test it
#printf '%s\n' '8.8.8.8 bogus-site.com' >> /etc/hosts.pending

# Verify it
awkexp='NR == FNR { allowed[$0]; next }

# If an IP is not in the list of allowed IPs then print it and exit
!($1 in allowed) && ! /\s*#/ && ! /^\s*$/ {
	print $1
	exit
}
'
disallowed=$(awk "$awkexp" /etc/hosts.allowed /etc/hosts.pending)
if [ "$disallowed" ]; then
	echo "$disallowed not allowed, see /etc/hosts.pending" >&2
	exit 1
fi

# Block sites from /etc/hosts.include
while read -r site; do
	printf '0.0.0.0 %s\n' "$site" >> /etc/hosts.pending
done < /etc/hosts.include

# Finalize it
mv /etc/hosts.pending /etc/hosts

