#!/bin/sh
# manjaro-i3 script for blurring the screen and locking it
# Now works with sway too. Also increased the blur.
# Original script: https://gitlab.manjaro.org/packages/community/i3/i3exit

# sway sets a "SWAYSOCK" variable, so just use that to detect sway
if [ "$SWAYSOCK" ]; then
	if ! command -v swaylock > /dev/null; then
		echo "swaylock must be installed" >&2
		exit 1
	elif ! command -v grim > /dev/null; then
		echo "grim must be installed" >&2
		exit 1
	fi
	locker=swaylock
	sway=true
else
	locker=i3lock
	i3=true
fi

# use ffmpeg if installed
if command -v ffmpeg > /dev/null; then
	use_ffmpeg=true
fi

# imagemagick is only required for i3, or if ffmpeg is not installed
if ! command -v import > /dev/null; then
	if [ "$i3" ] || [ ! "$use_ffmpeg" ]; then
		echo "imagemagick must be installed" >&2
		exit 1
	fi
fi

# take screenshot
if [ "$sway" ]; then
	grim /tmp/screenshot.png
else
	import -window root /tmp/screenshot.png
fi

# blur it
if [ "$use_ffmpeg" ]; then
	ffmpeg -loglevel fatal -y -i /tmp/screenshot.png \
		-filter_complex "boxblur=10" -vframes 1 \
		/tmp/screenshotblur.png
else
	convert /tmp/screenshot.png -blur 0x10 /tmp/screenshotblur.png
fi
rm /tmp/screenshot.png

# lock the screen
$locker -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
