#!/bin/sh
# manjaro-i3 script for blurring the screen and locking it
# Now works with sway too. Also increased the blur.
# Original script: https://gitlab.manjaro.org/packages/community/i3/i3exit

# sway sets a "SWAYSOCK" variable, so just use that to detect sway
if [ -n "$SWAYSOCK" ]; then
	if ! command -v swaylock > /dev/null; then
		echo "swaylock must be installed" >&2
		exit 1
	elif ! command -v grim > /dev/null; then
		echo "grim must be installed" >&2
		exit 1
	fi
	locker=swaylock
else
	locker=i3lock
fi

# take screenshot
if [ -n "$SWAYSOCK" ]; then
	grim /tmp/screenshot.png
else
	import -window root /tmp/screenshot.png
fi

# blur it
convert /tmp/screenshot.png -blur 0x10 /tmp/screenshotblur.png
rm /tmp/screenshot.png

# lock the screen
$locker -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
