#!/bin/sh -e

# Start of localizable text
help() {
	cat - >&2 <<EOF
doasedit - like sudoedit, but for doas

doasedit file...

Every argument will be treated as a file to edit. There's no support for
passing arguments to doas, so you can only doas root.

This script is SECURITY SENSITIVE! Special care has been taken to correctly
preserve file attributes. Please exercise CAUTION when modifying AND using
this script.
EOF
}
MSG_UNCHANGED='File unchanged, exiting...'
MSG_DONE='Done, changes written'
# End of localizable text

case "$1" in --help|-h) help; exit 0;; esac

export TMPDIR=/dev/shm/
TRAP_SIGS='EXIT HUP QUIT TERM INT ABRT'
trap "trap - $TRAP_SIGS; "'rm -f "$tmp" "$tmpcopy"' $TRAP_SIGS

for file; do
	case "$file" in -*) file=./"$file" ;; esac

	tmp="$(mktemp)"
	if [ -f "$file" ] && [ ! -r "$file" ]; then
		doas cat "$file" > "$tmp"
	elif [ -r "$file" ]; then
		cat "$file" > "$tmp"
	fi

	tmpcopy="$(mktemp)"
	cat "$tmp" > "$tmpcopy"

	${EDITOR:-vi} "$tmp"

	if cmp -s "$tmp" "$tmpcopy"; then
		echo $MSG_UNCHANGED
	else
		doas dd if="$tmp" of="$file"
		echo $MSG_DONE
	fi

	rm "$tmp" "$tmpcopy"
done

