#!/bin/sh -e
# Use the drive CLI tool and gpg to backup files/directories to Google
# Drive, encrypting + (highly) compressing them before sending them out
#
# This is meant for unattended use, so gpg should not need to prompt for
# a passphrase.
#

push() { drive push -no-prompt -force -hidden -piped "$@"; }
encrypt() {
	gpg2 --encrypt --default-recipient-self \
		-z 9 --batch --no-tty --yes
}

cd "${DRIVEDIR?Set \$DRIVEDIR to point to the mount directory for drive}"
mkdir -p ~/.dbackup

for path; do
	case "$path" in -*) path=./"$path" ;; esac
	bn=$(basename "$path")
	case "$bn" in -*) bn=./"$bn" ;; esac

	if [ -f ~/.dbackup/"$bn" ] && [ ! "$(find "$path" -newer ~/.dbackup/"$bn")" ]; then
		continue
	fi
	touch ~/.dbackup/"$bn"
	if [ -f "$path" ]; then
		encrypt < "$path" | push "$bn.gpg"
	elif [ -d "$path" ]; then
		tar -c "$path" | encrypt | push "$bn.tar.gpg"
	fi
done

