#!/bin/sh -e

help() {
	cat - >&2 <<EOF
flashcard - for memorizing things

flashcard file

The lines of the file should be formatted like front=back where
"front" is the information to be presented to you and "back" is the
corresponding information you should reply with. The script will tell
you whether or not you were correct, and present the correct answer to
you if you were incorrect.
EOF
}

case "$1" in
	--help|-h) help; exit 0;;
	*) ;;
esac

while :; do
	words=$(shuf < "$1" | head -n 1)
	front=${words%%=*}
	back=${words##*=}
	echo "$front"
	printf '> '
	read -r response
	case "$response" in
		"$back")
			printf '\n----------------\nCorrect!\n----------------\n\n'
			;;
		*)
			printf '\n----------------\nThe correct answer was %s\n----------------\n\n' "$back"
			;;
	esac
done
