#!/bin/sh
# Starts up Links in graphical mode with some nice colors

# For compatibility with Arch/Arch-based distros
if command -v xlinks; then
	links=xlinks
else
	links=links
fi

WHITISH=0xD3D0D0
LIGHTBLUE=0x3679FF
BLACKISH=0x090909

$links -g -html-g-text-color $WHITISH -html-g-link-color $LIGHTBLUE -html-g-background-color $BLACKISH $@

