#!/bin/sh
# Transparently edit a gpg encrypted file. I'm not a gpg expert, so
# don't trust this script and please let me know if I'm doing something
# wrong.

export TMPDIR=/dev/shm/
trap 'rm -rf "$tmpd"' EXIT TERM QUIT HUP INT ABRT
tmpd=$(mktemp -d)

gpg='gpg2 --no-tty --batch --yes'

$gpg -d "$1" > "$tmpd/plain"

cat "$tmpd/plain" > "$tmpd/plain_copy"

${EDITOR:-vi} "$tmpd/plain"

if ! cmp -s "$tmpd/plain" "$tmpd/plain_copy"; then
	$gpg --default-recipient-self -a -o "$1" -e "$tmpd/plain"
else
	echo 'File unchanged, exiting...' >&2
fi


