#!/bin/sh
# Requires socat

err() { printf 'listenman: %s\n' "$1" >&2; exit 1; }
mpv_send() { printf '%s\n' "$1" | socat - /tmp/listenman; }

help() {
	err 'listenman [OPTIONS] SUBCOMMAND

INFO:
	Similar to playerctl, but works with mpv too. Add 
	input-ipc-server=/tmp/listenman to your ~/.config/mpv/mpv.conf

OPTIONS:
	-h
		Shows this message

SUBCOMMANDS:
	next
	previous
	play-pause
	play
	pause
	stop'
}

while getopts 'h' o; do
	case "$o" in
		h | *) help;;
	esac
done
shift $((OPTIND-1))

command -v socat > /dev/null || err "socat must be installed"

touch /tmp/listenman

case "$1" in
	next)       mpv_send '{"command": ["playlist-next"]}';;
	previous)   mpv_send '{"command": ["playlist-prev"]}';;
	play-pause) mpv_send '{"command": ["cycle", "pause"]}';;
	play)       mpv_send '{"command": ["play"]}';;
	pause)      mpv_send '{"command": ["pause"]}';;
	stop)       mpv_send '{"command": ["stop"]}';;
	*)          err      'Invalid subcommand';;
esac

