#!/bin/sh
# This is a script for controlling mpv via a socket located at /tmp/listenman
# Be sure to add input-ipc-server=/tmp/listenman to your mpv.conf
# Requires socat

err()      { printf 'listenman: %s\n' "$1" >&2; exit 1;   }
mpv_send() { printf '%s\n' "$1" | socat - /tmp/listenman; }

command -v socat > /dev/null || err "socat must be installed"

: > /tmp/listenman

case "$1" in
	next)       mpv_send '{"command": ["playlist-next"]}';;
	previous)   mpv_send '{"command": ["playlist-prev"]}';;
	play-pause) mpv_send '{"command": ["cycle", "pause"]}';;
	play)       mpv_send '{"command": ["play"]}';;
	pause)      mpv_send '{"command": ["pause"]}';;
	stop)       mpv_send '{"command": ["stop"]}';;
	*)          err      'Invalid subcommand';;
esac

