#!/bin/sh -e
# mpvyt [-n num] query...
#
# Search for youtube videos and play them with mpv. Only plays 5 videos
# by default, can be increased to any number with the -n option (giving
# -n 0 will play an indefinite amount of videos)
#
# Beware that adding videos to the playlist takes time, so a high (or
# 0) -n value might cause the first video to take a while to load.

n=
while getopts 'n:' o; do
	case "$o" in
		n)
			if [ "$OPTARG" = 0 ]; then
				n='all'
			else
				n="$OPTARG"
			fi
			;;
		*)
			echo "Unrecognized option $o" >&2
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

if [ ! "$*" ]; then
	echo "Can't search for nothing" >&2
	exit 1
fi

mpv --force-window=immediate --no-resume-playback ytdl://ytsearch"${n:-5}":"$*"

