#!/bin/sh -e

help() {
	cat - >&2 <<EOF
mpvyt - search for youtube videos and play them with mpv

mpvyt [-n num] query...

Only plays 5 videos by default, which can be increased to any number
with the -n option (-n 0 will play an indefinite amount of videos)

Beware that adding videos to the playlist takes time, so a high (or
0) -n value might cause the first video to take quite a while to load.
EOF
}

unset -v n a
while getopts 'han:' o; do
	case "$o" in
		n)
			if [ "$OPTARG" = 0 ]; then
				n='all'
			else
				n="$OPTARG"
			fi
			;;
		a) a=1 ;;
		h) help; exit 0 ;;
		*) help; exit 1 ;;
	esac
done
shift $((OPTIND-1))

if [ ! "$*" ]; then
	echo "Can't search for nothing" >&2
	exit 1
fi

mpv --force-window=immediate --no-resume-playback \
	${a:+--video=no --force-window=no } \
	ytdl://ytsearch"${n:-5}":"$*"

