#!/bin/sh -Ce
# A shell script for making shell scripts. Automates creating a shebang +
# setting the execute bit. Won't overwrite existing files.

export POSIXLY_CORRECT=1

echo '#!/bin/sh -e' > "$1"
chmod u+x "$1"

unset -v POSIXLY_CORRECT
exec ${EDITOR:-vi} "$1"

