#!/bin/sh -Ce
# A shell script for making shell scripts. Automates creating a shebang +
# setting the execute bit. Won't overwrite existing files.

echo '#!/bin/sh -e' > "$1"
chmod u+x "$1"
exec ${EDITOR:-vi} "$1"

