#!/bin/sh -e

help() {
	cat - >&2 <<EOF
snotify - a simple notification system

snotify [-ndr]

snotify is a simple notification system designed for use with status
bars et al. and based around keeping notifications in a single file
located at ~/.snotify (snotify manages this file, don't modify it
manually).

The default behavior when supplied no arguments is to display the most
recent notification.

The following options are recognized:

-n msg...
	Add notification msg. Multiple arguments to this option will be
	joined by the first character of the IFS (usually whitespace).

-d
	Delete the most recent notification

-r
	Delete all notifications

-
	Concatenate stdin onto the end of the notification file
EOF
}

export POSIXLY_CORRECT=1

case "$1" in
	--help|-h) help; exit 0;;
	*) ;;
esac

NOTIFY_FILE=$HOME/.snotify

# read stdin before grabbing lock, since reading stdin may take a while
if [ "$1" = '-' ]; then
	STDIN=$(cat -)
	[ "$STDIN" ] || exit 1
fi

# try to use a good lock implementation, fall back to something dirtier
LOCK=$NOTIFY_FILE.lock
if command -v flock > /dev/null 2>&1; then
	exec 9> "$LOCK"
	while ! flock -n 9; do
		sleep 0.1
	done
else
	trap 'rm -f "$LOCK"' EXIT QUIT HUP INT TERM ABRT
	while ! (set -C; : > "$LOCK"); do
		sleep 0.1
	done
fi

if [ "$*" ]; then
	case "$1" in
		-n)
			shift 1
			# avoid recording duplicate messages
			if grep -Fxqe "$*" "$NOTIFY_FILE"; then
				exit 0
			fi

			printf '%s\n' "$*" >> "$NOTIFY_FILE";
			;;
		-d)
			new=$(sed '$d' "$NOTIFY_FILE")
			cat > "$NOTIFY_FILE" <<-EOF
				$new
			EOF
			;;
		-r)
			rm "$NOTIFY_FILE"
			;;
		-)
			# avoid recording duplicate messages
			printf '%s\n' "$STDIN" | while read -r line; do
				if grep -Fxqe "$line" "$NOTIFY_FILE"; then
					continue
				fi
				printf '%s\n' "$line" >> "$NOTIFY_FILE"
			done
			;;
		*)
			help
			exit 1
			;;
	esac
else
	: >> "$NOTIFY_FILE"
	tail -n 1 "$NOTIFY_FILE"
fi

