#!/bin/sh -e

help() {
	cat - >&2 <<EOF
stream_notify - show streams that are currently live

stream_notify

This script requires a line-separated list of stream URLs at ~/.streams
(or another file specified by the NOTIFYSTREAMS environment variable)
and youtube-dl. Each URL may be followed by an optional nickname for the
stream (e.g. http://website.com/stream123 stream123).

Examples using cron:
	# 0,30 * * * * means to run every 30 minutes

	# Using my snotify script
	0,30 * * * * stream_notify | snotify -

	# Using a simple file
	0,30 * * * * stream_notify > ~/.livestreams

	# Using nothing, expecting cron to send you mail
	0,30 * * * * stream_notify
EOF
}

if [ "$*" ]; then
	help; exit 1;
fi

exec < "${NOTIFYSTREAMS:-"${HOME:?}/.streams"}"
while read -r url stream; do
	# ideally would use title, but the titles returned by ytdl for twitch 
	# are not useful here
	desc=$(youtube-dl -q --get-description "$url" 2> /dev/null) || continue
	printf '%s\n' "${stream:-$url} is live: $desc"
done

