#!/bin/sh
# Takes a username argument and begins watching a Twitch stream for that username
# Prefers VLC but will fall back to MPV

url="https://twitch.tv/$1"

if command -v mpv; then
	vlc $url
elif command -v vlc; then
	mpv $url
else
	echo "Either VLC or MPV need to be installed" >&2
	exit 1
fi
