#!/usr/bin/env python3

# /usr/local/bin/verify_hosts

# verify_hosts hosts_file [allowed IPs]

# This script verifies that a hosts file does not map to any unauthorized IP
# addresses. Additional IP addressed may be allowed with the syntax described
# above. An exception is raised if the verification fails.

import sys

with open(sys.argv[1]) as f:
    text = f.read()

# Base list of allowed IPs
allowed = [
    '0.0.0.0', '127.0.0.1', '255.255.255.255', '::1', 'fe80::1%lo0', 'ff00::0',
    'ff02::1', 'ff02::2', 'ff02::3'
]

# Optionally take an argument extending the list of allowed IPs
if len(sys.argv) >= 3:
	allowed.extend(sys.argv[2].split())

for line in text.split('\n'):
    line = line.lstrip()
    try:
        ip = line.split()[0]
        if not line.startswith('#') and ip not in allowed:
            raise Exception(line)
    except IndexError:
        pass

