#!/bin/sh -e
#
# Usage: wepeeter [-p] REPEATS FILE...
#
# Makes REPEATS-many directories within the current directory containing 
# symlinks to the specified files. Naming scheme is "wepeet-$n"
#
# The main use of this is to give higher weight to preferred files when 
# passing a directory to a media player, e.g., your favorite songs get 
# played more often.
#
# If REPEATS is 0 then the number of repeats will be chosen 
# interactively per-file with the option to preview each file with a 
# user-specified program.
#

unset -v previewer
while getopts 'p:' o; do
	case "$o" in
		p) previewer="$OPTARG" ;;
		#h) help; exit 0 ;;
		#*) help; exit 1 ;;
	esac
done
shift $((OPTIND-1))

wepeet() {
	repeats="${1:?}"
	shift 1
	test "${1:?}"

	# remove existing symlinks for the specified files
	for dir in wepeets/*/; do
		case "$dir" in "wepeets/*/") break;; esac
		for file; do
			rm -f "$dir/$(basename "$file")"
		done
		# remove wepeet directories if they're empty
		rmdir "$dir" 2> /dev/null || :
	done

	i=1
	while [ "$i" -le "$repeats" ]; do
		mkdir -p "wepeets/wepeet-${i}"
		for file; do
			# prefix relative paths with ../../
			case "$file" in /*) ;; *) file="../../$file" ;; esac
			ln -sf "$file" "wepeets/wepeet-${i}/"
		done
		i=$((i+1))
	done
}

if [ "${1:?}" -eq 0 ]; then
	if [ ! "$previewer" ]; then
		echo 'Program for previewing files (leave blank to disable previews): ' >&2
		read -r previewer
	fi

	shift 1
	for file; do
		unset -v repeats
		while [ ! "$repeats" ]; do
			if [ "$previewer" ]; then
				( set -f; $previewer "$file"; )
			fi
			echo "Number of repeats for $file (leave blank to preview again): " >&2
			read -r repeats
			if [ "$repeats" ] && ! [ "$repeats" -ge 0 ]; then
				unset -v repeats
			fi
		done
		wepeet "$repeats" "$file"
	done
else
	wepeet "$@"
fi

