#!/bin/sh -ef
# This script builds/installs a list of packages using xbps-src. If a package
# is already built/installed then it will be ignored. If XBPS_DISTDIR hasn't
# been bootstrapped then it will be bootstrapped. This script won't manage
# your git repository for you.
#
# Requires:
# 1) xtools to be installed
# 2) xdistdir should be able to find a void-packages repository (i.e. set the
#    XBPS_DISTDIR environment variable)
# 3) XDISTUPGRADE_PKGS to be set to a space-seperated list of packages, the
#    variable should be defined in $XBPS_DISTDIR/etc/conf or ~/.xbps-src.conf
#    (searched in that order)

xdistdir="$(xdistdir)"
cd "$xdistdir"

# Source the xbps-src config file
# shellcheck disable=SC1090
if [ -f "$xdistdir"/etc/conf ]; then
	. "$xdistdir"/etc/conf
elif [ -f ~/.xbps-src.conf ]; then
	. ~/.xbps-src.conf
else
	. "$xdistdir"/etc/defaults.conf # last-ditch effort
fi

# Verify XDISTUPGRADE_PKGS has been set
[ "$XDISTUPGRADE_PKGS" ]

# Bootstrap
if [ -d ./masterdir ]; then
	./xbps-src bootstrap-update
else
	./xbps-src binary-bootstrap
fi

# Build
for pkg in $XDISTUPGRADE_PKGS; do
	# FIXME always compiles, even when not necessary
	./xbps-src -C pkg "$pkg"
done

# Install
# shellcheck disable=SC2086 # (globbing is disabled)
xi $XDISTUPGRADE_PKGS

