#!/usr/bin/env python3
# This script takes a URL argument to a YouTube channel/playlist and returns
# a link to the corresponding RSS feed.

from urllib.parse import urlparse
from sys import argv

# URLs:
# https://youtube.com/user/tuxreviews/videos
# https://youtube.com/channel/UC5UAwBUum7CPN5buc-_N1Fw
# https://youtube.com/playlist?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG

# RSS counterparts:
# https://youtube.com/feeds/videos.xml?channel_id=UC5UAwBUum7CPN5buc-_N1Fw
# https://youtube.com/feeds/videos.xml?user=tuxreviews
# https://youtube.com/feeds/videos.xml?playlist_id=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG

URL = argv[1]
PARSED = urlparse(URL)
PATH = [x for x in PARSED.path.split('/') if x]

if PATH[0] == 'user':
    ID = PATH[1]
    RSS = f"https://youtube.com/feeds/videos.xml?user={id}"
elif PATH[0] == 'channel':
    ID = PATH[1]
    RSS = f"https://youtube.com/feeds/videos.xml?channel_id={id}"
elif PATH[0] == 'playlist':
    ID = PARSED.query.lstrip('list=')
    RSS = f"https://youtube.com/feeds/videos.xml?playlist_id={id}"
else:
    raise ValueError('Invalid URL')

print(RSS)
